// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI_Multas.Infrastructure;

#nullable disable

namespace MinimalAPI_Multas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221128180616_ALTER_TABLE_MULTA")]
    partial class ALTER_TABLE_MULTA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MinimalAPI_Multas.Models.ApplicationModel.MultaModel", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMulta"), 1L, 1);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<double>("Monto")
                        .HasMaxLength(10)
                        .HasColumnType("float")
                        .HasColumnName("Monto");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Patente");

                    b.HasKey("IdMulta");

                    b.ToTable("Multa");
                });

            modelBuilder.Entity("MinimalAPI_Multas.Models.ApplicationModel.PrecioModel", b =>
                {
                    b.Property<int>("idPrecio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPrecio"), 1L, 1);

                    b.Property<double>("Monto")
                        .HasColumnType("float")
                        .HasColumnName("Monto");

                    b.HasKey("idPrecio");

                    b.ToTable("Precio");
                });
#pragma warning restore 612, 618
        }
    }
}
